### ISSUE TITLE
nvcc compilation fails

### ISSUE THREAD

**Issue by mariogeiger** [e3nn/e3nn#1]
https://github.com/mariogeiger/se3cnn/issues/49
@josejimenezluna

**Comment by L-sky** [comment]
@mariogeiger link leads to page 404, can you paste contents here if it is accessible for you

**Comment by mariogeiger** [comment]
This is weird. It seems that it disappeared

**Comment by josejimenezluna** [comment]
Hello @mariogeiger,

I keep having this compiling issue. Any progress?

**Comment by bkmi** [comment]
The most common reason this error occurs is because your installation of nvcc and pytorch do not match. [On this website](https://pytorch.org/get-started/locally/), you need to install a version of pytorch with cuda. In this case, it would be 10.1.

Then you need to [install cuda 10.1](https://developer.nvidia.com/cuda-toolkit-archive).

**Comment by mariogeiger** [comment]
@L-sky Can you write these instruction that @bkmi explained into the readme?
It looks like making a conda-forge package will be impossible while pytorch is not on conda-forge

**Comment by josejimenezluna** [comment]
Hey @bkmi,

Here is my nvcc version:

```
(base) jose@gpu0:~$ nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Nov__3_21:07:56_CDT_2017
Cuda compilation tools, release 9.1, V9.1.85
```

However `nvidia-smi` claims I'm using CUDA 10.1

```
(base) jose@gpu0:~$ nvidia-smi
Wed Feb 26 14:44:59 2020
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 435.21       Driver Version: 435.21       CUDA Version: 10.1     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 1080    Off  | 00000000:81:00.0 Off |                  N/A |
|  0%   36C    P8     8W / 198W |    479MiB /  8119MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+

```

I will try updating CUDA manually using the link you mentioned and report back.

**Comment by bkmi** [comment]
The reason for this is probably because of where your path is looking for nvcc. You can have multiple nvcc's installed at the same time. Check your path and how it is setup by editing ```~/.bashrc```.

For example my .bashrc does this:
```
# CUDA
export PATH=/usr/local/cuda-10.1/bin:/usr/local/cuda-10.1/NsightCompute-2019.1${PATH:+:${PATH}}
export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64\
                         ${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}
```

Notice how I have explicitly set ```cuda-10.1```. It sometimes uses a shortcut path which can go out of date, or it is explicitly pointing at the old nvcc.

**Comment by josejimenezluna** [comment]
Hey @bkmi,

Installing the right version of `nvcc` solved the problem. For some reason, the nvidia toolkit pacakage available on the ubuntu bionic repos is still 9.2 instead of matching the CUDA version on the latest stable driver.

Thanks for your help.

**Comment by mariogeiger** [comment]
> 
> However `nvidia-smi` claims I'm using CUDA 10.1
> 

What `nvidia-smi` shows is the last version of CUDA that your driver can support. It has nothing to do with the actual version of cuda installed.

**Comment by mariogeiger** [comment]
he have a separate `setup_cuda.py` now
