### ISSUE TITLE
write user-friendly instructions for installing needed software for compiling cuda extensions

### ISSUE THREAD

**Issue by blondegeek** [e3nn/e3nn#10]
If possible, summarize in a brief paragraph to be put in the readme what is needed to install cuda extensions -- provide links to needed websites, but avoid relying on the user going to that site to get an overview of what is needed: e.g. provide a copy of the commands on the nvidia cuda install site. The users will thank you for an unintimidating, straightforward, and concise overview of what is needed.

**Comment by mariogeiger** [comment]
Make cuda compilation optional, such that by default `python setup.py install` does not compile cuda code even if there is a GPU present

**Comment by mariogeiger** [comment]
Installing manually cuda finally worked.

**Comment by mariogeiger** [comment]
We have a separate `setup_cuda.py` file now
