### ISSUE TITLE
Question about equivariance in point convolution layer

### ISSUE THREAD

**Issue by Nanco-L** [e3nn/e3nn#102]
Hello, I just read paper about SE(3) equivariant neural network (3D steerable CNN, Tensor field network, etc) and test this repository. 

First, I try to play with example code in the front page of this github.
What I tried is add random rotation in the example code like below.

```python
# unmentioned part of example code is same with that in front page

from e3nn.o3 import rand_rot

Rs_in = [(3, 0)]  # Input = Three scalars
Rs_out = [(1, 1)]  # Output = One single vector

features = rs.randn(1, n, Rs_in, requires_grad=True)
in_geometry = torch.randn(1, n, 3)
out_geometry = torch.zeros(1, 1, 3)  # One point at the origin

rot_in_geometry = torch.bmm(rand_rot().unsqueeze(0), in_geometry.transpose(1,2)).transpose(1,2)

out = norm(conv(features, in_geometry, out_geometry)
out_rot = norm(conv(features, rot_in_geometry, out_geometry))
```

In that case, `out` and `out_rot` show same result.
However, when I try to add vector in `Rs_in` like below, I cannot get equivariant result (`out != out_rot`).

```python
# unmentioned part of example code is same with that in front page

from e3nn.o3 import rand_rot

Rs_in = [(1, 1)]  # Input = One single vector
Rs_out = [(1, 1)]  # Output = One single vector

features = rs.randn(1, n, Rs_in, requires_grad=True)
in_geometry = torch.randn(1, n, 3)
out_geometry = torch.zeros(1, 1, 3)  # One point at the origin

rot_matrix = rand_rot()

rot_features = torch.bmm(rot_matrix.unsqueeze(0), features.transpose(1,2)).transpose(1,2)
rot_in_geometry = torch.bmm(rot_matrix.unsqueeze(0), in_geometry.transpose(1,2)).transpose(1,2)

out = norm(conv(features, in_geometry, out_geometry)
out_rot = norm(conv(rot_features, rot_in_geometry, out_geometry))
```

Is this result is correct? What I understand is the norm of the outputs from se(3)-equivariant layer with se(3) transformed inputs always same. However, the result confuses me. I know this question is rather basic but I need someone's help.

**Comment by mariogeiger** [comment]
Hi, thanks for asking this question!

The reason is that the representation acting on the input space (given by `o3.rand_rot`, `o3.rot`, `o3.rot_y`, ... functions) is not equal to the representation acting on the L=1 features (given by the function `o3.irr_repr`).

```
o3.rot(alpha, beta, gamma) != o3.irr_repr(1, alpha, beta, gamma)
```

The two representations are however isomorphic. The change of basis between the two is given by the function `o3.xyz_vector_basis_to_spherical_basis`

```
A = o3.xyz_vector_basis_to_spherical_basis()
A @ o3.rot(alpha, beta, gamma) @ A.T == o3.irr_repr(1, alpha, beta, gamma)
```

`A` simply permutes the directions `(x,y,z) -> (y,z,x)`:
```
A = [[0, 1, 0],
     [0, 0, 1],
     [1, 0, 0]]
```
