### ISSUE TITLE
Optimize KernelFn with cuda

### ISSUE THREAD

**Issue by mariogeiger** [e3nn/e3nn#11]
Implementing `KernelFn` in cuda might accelerated the computations?

**Comment by blondegeek** [comment]
Since we've gotten the Kernel down to a single einsum -- do we need to do this or should we rather see how far we can get with opt einsum?

**Comment by mariogeiger** [comment]
the einsum method uses a matrix with plenty of zeros. The cuda implementation can therefore in principle be faster.
