### ISSUE TITLE
[idea] use sympy

### ISSUE THREAD

**Issue by mariogeiger** [e3nn/e3nn#12]
Use sympy to compute wigner d matrix and clebsch gordan coefficients

https://docs.sympy.org/latest/modules/physics/wigner.html#sympy.physics.wigner.wigner_d
https://docs.sympy.org/latest/modules/physics/wigner.html#sympy.physics.wigner.clebsch_gordan
https://docs.sympy.org/latest/modules/physics/wigner.html#sympy.physics.wigner.wigner_3j
https://docs.sympy.org/latest/modules/functions/special.html#sympy.functions.special.spherical_harmonics.Znm

**Comment by blondegeek** [comment]
I don’t think sympy has winger D’s and CG for real spherical harmonics, but
we could also make them from the appropriate summations over pairs of
complex spherical harmonics.
