### ISSUE TITLE
infer change of basis code

### ISSUE THREAD

**Issue by blondegeek** [e3nn/e3nn#128]
Create classes that help others infer the change of basis between different spherical harmonic conventions. @mariogeiger this would be based on your prior code for doing this.

**Comment by mariogeiger** [comment]
There is already a function `o3.intertwiners` that computes the change of basis between two representations.

Also now `rs.reduce_tensor` accepts callables as representations so you can do things like:

```
rs.reduce_tensor('i', i=o3.rot, has_parity=False)
#([(1, 1, 0)],
# tensor([[0., 1., 0.],
#         [0., 0., 1.],
#         [1., 0., 0.]]))
```

**Comment by blondegeek** [comment]
Ah! So, that's where it is. Thanks!

Something to add to the tutorial todo list: develop a tutorial for how to
use this on some example cases.

Re accepting callables: that's great!
