### ISSUE TITLE
Error with data_helpers

### ISSUE THREAD

**Issue by daniil-777** [e3nn/e3nn#140]
While running the script tetris_torch_geo.py from examples I encounter the following error:

<img width="1675" alt="Screenshot 2020-10-21 at 17 40 21" src="https://user-images.githubusercontent.com/25828280/96743680-8ae95f80-13c4-11eb-9122-611b6583c3a2.png">

Could you please help with that?

**Comment by blondegeek** [comment]
Removed `size` arg in commit https://github.com/e3nn/e3nn/commit/366bf291faec8a4d7c47bea6943978064bd92d94
