### ISSUE TITLE
Add `find_peaks` method  to S2Grid and SphericalTensor

### ISSUE THREAD

**Issue by blondegeek** [e3nn/e3nn#158]
We use to have a peak finding function in [se3cnn](https://github.com/mariogeiger/se3cnn/blob/point/se3cnn/spherical_harmonics.py#L43) to detect the peaks of what is now a `SphericalTensor`. `SphericalTensor` already has a [`signal_on_grid`](https://github.com/e3nn/e3nn/blob/master/e3nn/tensor/spherical_tensor.py#L166) method, but at least previously, we would use two separate grids to catch peaks that were on the seam. What's the easiest way to put this feature back in the repo?

**Comment by mariogeiger** [comment]
It would be a method of SphericalTensor

**Comment by mariogeiger** [comment]
Done in #a718515a069bc9dc7d625e718228ff95396917b1
