### ISSUE TITLE
Create conda-forge version

### ISSUE THREAD

**Issue by blondegeek** [e3nn/e3nn#16]

**Comment by bkmi** [comment]
There is another option from conda-forge called poetry. Someone in my lab recommended it. Perhaps it would work for us?

https://python-poetry.org/

**Comment by mariogeiger** [comment]
Cool can we compile cuda and distribute compiled code?
The problem with conda-forge is that we need pythorch to be added to conda-forge

**Comment by blondegeek** [comment]
Would it make sense create a conda package that simply does not have any of the CUDA components?

**Comment by mariogeiger** [comment]
Then pip would be even better ??

**Comment by bkmi** [comment]
The more I read the more I think we should target pip as initial release. It seems conda has tools to help covert a pip package to conda.

If the goal is to release something on pip asap, I say we go ahead without including the binaries.

If the goal is to release the fastest version of the software, we should figure out the binaries first.

I vote for putting the software on pip without custom cuda acceleration and allow more serious users to compile it themselves. We can accomplish this by introducing a check for the binaries when the spherical harmonic function is called.

**Comment by mariogeiger** [comment]
I close the issue because we give up with conda-forge
