### ISSUE TITLE
Non-determinism in `CartesianTensor.to_irrep_transformation()`

### ISSUE THREAD

**Issue by blondegeek** [e3nn/e3nn#161]
It seems that `rs.reduce_tensor` is producing non-deterministic transformation matrices.
https://gist.github.com/blondegeek/562266e2cdd597299501171b8528938a

Q and Irrep Tensors derived from `torch.ones(3, 3, 3, 3)` and `ijkl=jikl=klij`
![image](https://user-images.githubusercontent.com/4080470/102274297-7ca55480-3ed8-11eb-81b5-1101fb516504.png)

**Comment by blondegeek** [comment]
I am running Python 3.7.5 and @nimalec who is seeing the same issue is running Python 3.7.6

**Comment by blondegeek** [comment]
I've added a test here (latest commit). The test fails for my installation.
https://github.com/blondegeek/e3nn/tree/cartten_test

**Comment by blondegeek** [comment]
As confirmed with @mariogeiger this is a issue of degeneracy in how `Q` is defined and that when you call `CartesianTensor.to_irrep_transformation()` and `CartesianTensor.to_irrep_tensor()` you may not get the same transformation matrix `Q`.

**Comment by blondegeek** [comment]
To do: Add this detail to docs and consider re-writing methods to help prevent this issue.

**Comment by mariogeiger** [comment]
I think this has been fixed at some point. Please reopein if there is still an issue.
