### ISSUE TITLE
Examples/point/atom_types does not work

### ISSUE THREAD

**Issue by mattbernardini** [e3nn/e3nn#163]
I have tried running the code but it gives me an error saying:
Traceback (most recent call last):
  File "test.py", line 49, in <module>
    mix1 = Mixer(C, [Rs_in1, Rs_in2], act1.Rs_in)
  File "test.py", line 25, in __init__
    self.ops = torch.nn.ModuleList([
  File "test.py", line 26, in <listcomp>
    Op(Rs_in, Rs_out)
TypeError: __init__() takes 2 positional arguments but 4 were given

**Comment by mariogeiger** [comment]
Hi, sorry about that. I will soon write a new example using e3nn_core

**Comment by mariogeiger** [comment]
Here I made an example https://github.com/e3nn/e3nn_core/blob/main/examples/atom_types.py
