### ISSUE TITLE
Add pytorch-geometric to INSTALL.md

### ISSUE THREAD

**Issue by RealPolitiX** [e3nn/e3nn#166]
Since ``pytorch-geometric`` is a core external dependency, I suggest adding explicit instructions on how to install it in ``INSTALL.md``, such as [here](https://gist.github.com/RealPolitiX/c2a85c77e3f418accc16b664da127e16).

**Comment by mariogeiger** [comment]
Hi, indeed it's useful! I actually did it now in [e3nn_core INSTALL.md](https://github.com/e3nn/e3nn_core/blob/main/INSTALL.md)
e3nn_core will replace most of e3nn.
