### ISSUE TITLE
❓ [QUESTION] Input point cloud data with 1024 points to the example Network then reported an error:  out of memory

### ISSUE THREAD

**Issue by mrclovvn** [e3nn/e3nn#182]
Hi! @blondegeek

  Thanks for your great work! I have done some simple experiments with e3nn recently, which is very effective on point cloud data.

  However, it seems that consumed too much memory in CUDA when I used it on point cloud data. I just replaced the input in  [e3nn/examples/point/tetris_parity.py](https://github.com/e3nn/e3nn/blob/master/examples/point/tetris_parity.py) with 1024 points, the network was as follows:
````
class Network(torch.nn.Module):
    def __init__(self, num_classes):
        super().__init__()

        R = partial(CosineBasisModel, max_radius=3.0, number_of_basis=3, h=100, L=3, act=relu)
        K = partial(Kernel, RadialModel=R)

        mul = 7
        layers = []

        Rs = [(1, 0, +1)]
        for i in range(3):
            scalars = [(mul, l, p) for mul, l, p in [(mul, 0, +1), (mul, 0, -1)] if haspath(Rs, l, p)]
            act_scalars = [(mul, relu if p == 1 else tanh) for mul, l, p in scalars]

            nonscalars = [(mul, l, p) for mul, l, p in [(mul, 1, +1), (mul, 1, -1)] if haspath(Rs, l, p)]
            gates = [(sum(mul for mul, l, p in nonscalars), 0, +1)]
            act_gates = [(-1, sigmoid)]

            print("layer {}: from {} to {}".format(i, rs.format_Rs(Rs), rs.format_Rs(scalars + nonscalars)))

            act = GatedBlockParity(scalars, act_scalars, gates, act_gates, nonscalars)
            conv = Convolution(K(Rs, act.Rs_in))
            block = torch.nn.ModuleList([conv, act])
            layers.append(block)
            Rs = act.Rs_out

        act = GatedBlockParity([(mul, 0, +1), (mul, 0, -1)], [(mul, relu), (mul, tanh)], [], [], [])
        conv = Convolution(K(Rs, act.Rs_in))
        block = torch.nn.ModuleList([conv, act])
        layers.append(block)

        self.firstlayers = torch.nn.ModuleList(layers)

        # the last layer is not equivariant, it is allowed to mix even and odds scalars
        self.lastlayers = torch.nn.Sequential(AvgSpacial(), torch.nn.Linear(mul + mul, num_classes))


I also tried input 512 points, but it still consumes about 10G memory, is there any problem?
Could you please give me some help? Thanks very much!

Best wishes!

**Comment by blondegeek** [comment]
Hi @mrclovvn,

This specific network uses all possible pairwise distances between points -- I'm guessing this is why it's blowing up when you try 512+ points. I'd recommend trying out this code example instead which uses a radial cutoff for defining nearest neighbors:
https://github.com/e3nn/e3nn/blob/master/examples/point/tetris_torch_geo.py

Please feel free to reopen this issue if using the `torch_geometric` version of this task (above) does not solve the problem.

**Comment by mrclovvn** [comment]
> Hi @mrclovvn,
> 
> This specific network uses all possible pairwise distances between points -- I'm guessing this is why it's blowing up when you try 512+ points. I'd recommend trying out this code example instead which uses a radial cutoff for defining nearest neighbors:
> https://github.com/e3nn/e3nn/blob/master/examples/point/tetris_torch_geo.py
> 
> Please feel free to reopen this issue if using the `torch_geometric` version of this task (above) does not solve the problem.

Thanks for your reply! 

I tried the code in `tetris_torch_geo.py` and modified some parameters ,  then there was no the OOM error even when I input 10k points, and it brought me excellent results beyond expectations!

 But at this time [the step](https://github.com/e3nn/e3nn/blob/447ccb253061a50b29f3a05c6eeffba34cca2c14/examples/point/tetris_torch_geo.py#L47)(line 47) as follows takes too much time for about 2 minutes: 

 `batch = Batch.from_data_list([DataNeighbors(x, shape, r_max, self_interaction=False) for shape in shapes])` 

Is there any better way to make it faster?

**Comment by blondegeek** [comment]
Hi @mrclovvn,

This has more to do with torch and torch_geometric than e3nn. To speed up
the data pre-process I’d recommend implementing your own class to replace
DataNeighbors. if you look into the code, you’ll see it’s a fairly simple
class that inherits from torch_geometric.data.Data. You can likely use
torch_geometric.nn.radius_graph and read the torch_geometric and torch
documentation for best practices for loading and storing theses objects.

Hope that helps!
