### ISSUE TITLE
pdf for documents

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [e3nn/e3nn#194]
Hello,

I have a small request: would it be possible to provide the pdf for the e3nn? I personally find going through the pdf takes less time than browsing documents online. Thank you!

**Comment by mariogeiger** [comment]
Hi,

We'll tell you when we have such a document :)
Did you read this article https://arxiv.org/abs/1802.08219 ?

**Comment by Chen-Cai-OSU** [comment]
Thanks!
Of course I read the TFN paper:-) I even made a paper list for equivariant nets. https://github.com/Chen-Cai-OSU/awesome-equivariant-network

**Comment by mariogeiger** [comment]
Oh yes true I saw that list :-)
