### ISSUE TITLE
🌟 Execute notebooks in the test suit

### ISSUE THREAD

**Issue by mariogeiger** [e3nn/e3nn#198]
Use pytest-notebook to execute the notebooks present in the docs

**Comment by bdice** [comment]
I've used [nbval](https://github.com/computationalmodelling/nbval) for this task and had a good experience with it. It looks like the feature sets are quite similar. From what I can see on GitHub, nbval seems to have a larger user base (used by 800 packages, 22 contributors) and is stable (> 1.x), while pytest-notebook is 0.x and lists 2 contributors / no "used by" packages. I have no strong preference between the two, just wanted to share my experience with nbval. :)

Here's the command I used: https://github.com/glotzerlab/signac-examples/blob/5478bb68517789fdd5b2831059059f062e46153a/.circleci/config.yml#L59

**Comment by mariogeiger** [comment]
Thanks!

This issue is actually kind of outdated since now I would like to mode to exclusively use `.. jupyter-execute::` rather than notebooks
