### ISSUE TITLE
Create functions for generating Clebsch-Gordon matrices for specified Rs_1 and Rs_2 with truncation options

### ISSUE THREAD

**Issue by blondegeek** [e3nn/e3nn#2]
I want a function similar to [this](https://github.com/blondegeek/se3cnn/blob/manipulations/e3nn/util/manipulations.py#L84) and I would prefer that it be a function rather than a class (because I will use it outside of network functions).

**Comment by mariogeiger** [comment]
Added function `SO3.sorted_truncated_tensor_productRs` in c7910d94280aea7763b4d5ca9dadba230c4f20e4
