### ISSUE TITLE
geometry_in and geometry_out feature of convolution ❓ [QUESTION]

### ISSUE THREAD

**Issue by siddanib** [e3nn/e3nn#208]
Hello,

Thank you very much for making this code available for everyone. It has been extremely helpful for my work. I wanted to get some pointers on how to implement the geometry_in and geometry_out feature of convolution that was available before refactoring.

Application background:
Discrete spherical particles in a continuous fluid. geometry_in will be particle locations and geometry_out is arbitrary positions in the fluid.

Regards,
Bhargav

**Comment by mariogeiger** [comment]
Hi,

For this you will have to create a graph (`edge_src` and `edge_dst`) between your two set of points `geometry_in` and `geometry_out`.

The `Convolution` implemented in the proposed model indeed assumes that the input and output nodes are the same.

Here is one way to make it:
- I use the function [`radius`](https://pytorch-geometric.readthedocs.io/en/latest/modules/nn.html?highlight=radius#torch_geometric.nn.pool.radius) to create the graph
- `edge_src` point to nodes in `geometry_in` and `edge_dst` points to node in `geometry_out`
```python
from torch_cluster import radius
from torch_scatter import scatter

from e3nn import o3

irreps_in = o3.Irreps('1e + 1o')
irreps_pos = o3.Irreps('1o')
irreps_out = o3.Irreps('0e + 1e + 1o')

tp = o3.FullyConnectedTensorProduct(irreps_in, irreps_pos, irreps_out)

n = 25
features_in = irreps_in.randn(n, -1)
geometry_in = irreps_pos.randn(n, -1)
geometry_out = irreps_pos.randn(10, -1)

print(features_in.shape)  # torch.Size([25, 6])
print(geometry_in.shape)  # torch.Size([25, 3])
print(geometry_out.shape) # torch.Size([10, 3])

edge_index = radius(geometry_out, geometry_in, r=1.1)
edge_src = edge_index[0]
edge_dst = edge_index[1]
print(edge_index.shape)  # torch.Size([2, num_edge])
print(edge_src.shape)    # torch.Size([num_edge])
print(edge_dst.shape)    # torch.Size([num_edge])

edge_vec = geometry_in[edge_src] - geometry_out[edge_dst]
print(edge_vec.shape)  # torch.Size([num_edge, 3])

edge_feature = tp(features_in[edge_src], edge_vec)
print(edge_feature.shape)  # torch.Size([num_edge, 7])

features_out = scatter(edge_feature, edge_dst, dim=0, dim_size=geometry_out.shape[0])
features_out /= 3.5**0.5

print(features_out.shape)  # torch.Size([10, 7])
```

An alternative way that you can consider would be to concatenate `geometry_in` and `geometry_out` in one then create a big graph and filter the edges.
```python
pos = torch.cat([geometry_in, geometry_out])

edge_index = radius_graph(pos, r=1.1)
edge_src = edge_index[0]
edge_dst = edge_index[1]

mask = (edge_src < geometry_in.shape[0]) & (edge_dst >= geometry_in.shape[0])
edge_src = edge_src[mask]
edge_dst = edge_dst[mask]
```

**Comment by siddanib** [comment]
Thanks, Mario.

Regards,
Bhargav

**Comment by mariogeiger** [comment]
Here is an example of Convolution https://github.com/e3nn/e3nn/blob/main/e3nn/nn/models/conv_points_in_out.py
Adapted from https://github.com/e3nn/e3nn/blob/main/e3nn/nn/models/gate_points_2102.py
that handle different input and output nodes.

  Basically the main difference is that there is no more self-connections
