### ISSUE TITLE
❓ [QUESTION/BUG] evaluate the network without the features of nodes

### ISSUE THREAD

**Issue by F14r3** [e3nn/e3nn#221]
Hey, I have recently updated e3nn from v0.1.1 to v0.2.3 and was doing some analysis on molecules using atom positions and atom type. 

**Task**
make a graph representation of molecules and train them end-to-end on the equivariant neural networks

**Environment**
Ubuntu, python 3.8.5,  e3nn 0.2.3, pytorch 1.7.1, torch_geometric 1.6.3  

**Issue encountered**
I was hoping to generate a graph using the atom positions `'pos'` and the atom type `'z'` without the input features of the nodes `'x'`.  The network complains about that and did not run. I may have set it wrongly, please refer to my `network_wo_x()`.  A sample notebook is shared here https://gist.github.com/F14r3/29da069aca8d8ed23264989d817c2ce0  

A quick fix is to have ones to fill the`'x'`. It seems the program intends to do so as well in gate_points_2101, 2102, and v2103
```
/e3nn/nn/models/gate_points_2102.py in forward(self, data)
    318             x = data['x']
    319         else:
--> 320             assert self.irreps_in is None
    321             x = data['pos'].new_ones((data['pos'].shape[0], 1))
    322 

AssertionError: 
```
But the dimension might be wrong, the 1 in news_ones(shape, 1) should be corresponding to the number of irreps in the `irreps_in`. In my case, `irreps_in = o3.Irreps("3x0e + 2x1o")` gives 9. If I set that to 9, it starts to work. 

**Further question**
By manually tweaking the input features of the nodes, I am able to run the program for a single molecule and the equivariance error is checked. 
However, I would like to expand the capability to train multiply molecules, each with different number of atoms, in one batch. Could you suggest the best way to do that? Examples would be great. I used to have DataNeighbors under point/data_helpers in v0.1.1 to create a Batch then pass the generated `batch.x, batch.edge_index, batch.edge_attr` to the model.

Thank you!

Yu Yang

**Comment by Linux-cpp-lisp** [comment]
If you replace 
```python
assert self.irreps_in is None
x = data['pos'].new_ones((data['pos'].shape[0], 1))
```
with
```python
x = data['pos'].new_ones((data['pos'].shape[0], self.irreps_in.dim))
```
you will be able to generate default features of just ones with the right shape. You can also use this logic to construct these starting-point features outside of the model:
```python
model = ...
# ...
data['x'] = torch.ones((len(data['pos']), model.irreps_in.dim))
# ...

```

**Comment by Linux-cpp-lisp** [comment]
For batching, you can use [`torch_geometric.data.Batch`](https://pytorch-geometric.readthedocs.io/en/latest/notes/introduction.html#mini-batches)

**Comment by F14r3** [comment]
Thanks Alby for clearing it up.
It appears to me the dim, 1, has been hard-coded for 'x', 'z' in `gate_points_2101.py, gate_points_2102.py,` and 
https://github.com/e3nn/e3nn/blob/e80c3a704327958485c31afe61e95dba60f87bc8/e3nn/nn/models/v2103/gate_points_networks.py#L79

These classes might just be for demo purposes. If we want to be generic, maybe we can update that in the next version.

**Comment by Linux-cpp-lisp** [comment]
Glad to be able to help!

The hard-coding of `1` is in the context of the `assert self.irreps_in is None` that proceeds it; I think it's meant to deal with there not being input feature irreps, rather than having the irreps but not the features themselves.

**Comment by mariogeiger** [comment]
you have to set `irreps_in` to `None` if you don't give `'x'`
