### ISSUE TITLE
🌟 [FEATURE] Make FullTensorProduct and ElementwiseTensorProduct able to handle irreps as filter_ir_out, to make the functions consistent with the other tensorproduct functions

### ISSUE THREAD

**Issue by tueboesen** [e3nn/e3nn#266]
Trying to do something like this fails:
`tp = ElementwiseTensorProduct("1x0e+1x1o","1x0e+1x1o","1x0e+1x0e+1x1e")`
whereas doing this one works:
`tp = FullyConnectedTensorProduct("1x0e+1x1o","1x0e+1x1o","1x0e+1x0e+1x1e")`

And the reason why it fails is because the last string gets converted into an irreps, which is then iterated through and passed to irrep, like this (however the element passed into Irrep is still an Irreps):
```
a = o3.Irreps("1x0e+1x1o")
for ir in a:
    b = o3.Irrep(ir)
```
However Irrep cannot handle Irreps as input even when the Irrreps is just a single element.

There are two ways to fix this as far as I can see, either you allow o3.Irrep to accept o3.Irreps as input, provided the irreps is only a single element, or if this solution is unacceptable, you can make sure that the iteration of Irreps in ElementwiseTensorProduct, does not actually pass an Irreps in, but rather a string or any of the other valid possible inputs.

If this is fixed for both ElementwiseTensorProduct and FullTensorProduct it would enable the different tensorproducts to all accept similar types of input, which I think would be nice for consistency.
https://docs.e3nn.org/en/stable/api/o3/o3_tp.html?highlight=elementwise#e3nn.o3.ElementwiseTensorProduct

Edit: I realize that the output filter wasn't the best, since it was inconsistent for the particular case, so I changed it to something more sensisble.

**Comment by mariogeiger** [comment]
The interface I have now for `ElementwiseTensorProduct` and `FullTensorProduct` is the best I found (so far).

There is one problem with the notation you propose.

Let consider the following example
```
ElementwiseTensorProduct("1e + 1e", "1e + 1e", "0e + 1e + 2e")
```

It is ambiguous to interpret to which inputs `1e`  belong.

**Comment by tueboesen** [comment]
> The interface I have now for `ElementwiseTensorProduct` and `FullTensorProduct` is the best I found (so far).
> 
> There is one problem with the notation you propose.
> 
> Let consider the following example
> 
> ```
> ElementwiseTensorProduct("1e + 1e", "1e + 1e", "0e + 1e + 2e")
> ```
> 
> It is ambiguous to interpret to which inputs `1e` belong.

I guess it is because I don't understand exactly how the current interface works then. The documentation tells that the output component for ElementwiseTensorProduct should be an iterator of Irrep, unfortunately there is not an example of what exactly is meant by this. I just tested what I thought it meant, but that isn't working.

```
filter = iter([o3.Irrep("0e"),o3.Irrep("0e"),o3.Irrep("1o"),o3.Irrep("1o")])
tp3 = FullTensorProduct("1x1o","1x1o",filter)
```

**Comment by mariogeiger** [comment]
Your example work properly. I think I should improve the doc then.

`FullTensorProduct` computes all the possible tensor product component only once without making any linear combination. 

For instance in your example `1 x 1 = 0 + 1 + 2` and using the filter argument you can get rid of some component. In your example you endup only with the scalar because the others does not match with any element of the filter

**Comment by tueboesen** [comment]
> Your example work properly. 
Sorry, you are right, I was for some reason expecting more output from it. 

I still don't understand how this iterator works when it comes to filtering. How would I define the filter in the following case to only take the first scalar and the second vector of the output?
```
filter = ? 
ElementwiseTensorProduct("1e + 1e", "1e + 1e",filter)
```

**Comment by mariogeiger** [comment]
This is indeed impossible through the interface of `ElementwiseTensorProduct`. `filter` is only a convenient option that I added for typical needs but if clearly not versatile.

So far (new interface ideas are welcome) the only way to do what you want is through the base class `TensorProduct` and specifying by hand the `instructions` 

```python
o3.TensorProduct(
    "1e + 1e",
    "1e + 1e",
    "0e + 1e",
    [(0, 0, 0, 'uuu', False), (1, 1, 1, 'uuu', False)],
    internal_weights=False
)
```

![image](https://user-images.githubusercontent.com/333780/116665000-80bea400-a999-11eb-8731-c087dfba9d88.png)

**Comment by tueboesen** [comment]
In that case I don't really understand what exactly you are gaining by using an iterator of irrep for this kind of thing?
Wouldn't the following be equivalent in their information then?
filter = iter([o3.Irrep("0e"),o3.Irrep("1o")])
filter = "0e+1o"

**Comment by mariogeiger** [comment]
This is just a coding style :-)
I don't want filter to be an Irreps because the multiplicities makes no sense in this situation.
I want a set of Irrep but Irreps class is an ordered list of Irrep with multiplicities.
In general in code I like that the arguments of the function are exactly what is asked for and not more (no extra unused information). 

Note that you can simplify a little bit your `filter` variable and it will work as well because constructor is flexible:
```
filter = ["0e", "1o"]
```
The correct type of `filter_ir_out` should be:
```
something that we can iterate through and that contains stuff that can be converted into the `Irrep` class
```

**Comment by tueboesen** [comment]
Great that was exactly the information I was looking for.

> Note that you can simplify a little bit your filter variable and it will work as well because constructor is flexible:
> 
> filter = ["0e", "1o"]
> 
> The correct type of filter_ir_out should be:
> 
> something that we can iterate through and that contains stuff that can be converted into the `Irrep` class
> 

Maybe including something like that in the documentation would be nice for the next one :)

**Comment by mariogeiger** [comment]
I'll do that
