### ISSUE TITLE
❓ [QUESTION] how to represent molecular hamiltonian with e3nn

### ISSUE THREAD

**Issue by iorin0217** [e3nn/e3nn#276]
Hi

Thank you for opening the valuable framework!
I want to reproduce the below animation (rotating molecular hamiltonian). 
[https://slides.com/mariogeiger/h#/2](https://slides.com/mariogeiger/h#/2)
Is there some example code?

Any hints would be much appreciated.

**Comment by mariogeiger** [comment]
Hi,

This was part of some unpublished work.
Basically you have to create new kind of layers that output a tensor with two atom indices.

**Comment by iorin0217** [comment]
Oh, I see.

Thank you for your reply.
I'm looking forward to the publication.
