### ISSUE TITLE
❓ [QUESTION] Inverse of tensorproducts

### ISSUE THREAD

**Issue by tueboesen** [e3nn/e3nn#279]
I'm currently looking into which reversible operations you can perform on geometric objects.
By reversible I mean operations that have some sort of inverse operation or nearly inverse operation such that I if I apply both of them to a geometric object I should end with essentially the same object (provided I go from low-dimension to high dimension and back again)

For normal scalars, one example of this could be size 1 convolution and the transpose_convolution which a reversible operations when they share the same weights.

So essentially I'm looking for operations where I can do the following:

```
x # Low dimensional geometric object
y =  F(x) # y is a high dimensional geometric object
x2 = Finv(y, F.weight) # Finv should bring y back to the same dimension as x had, and when used with the weights of F then x=x2

```

I thought for sure that tensproducts must be reversible as well in a similar way to the convolution, but after looking at it for a while I'm not quite sure anymore.

```
irrep = "1x1o"
irrep_hd = '1x0e+1x1e+1x2e'
F = FullyConnectedTensorProduct(irrep,irrep,irrep_hd) 
Finv = FullyConnectedTensorProduct(irrep_hd,irrep_hd,irrep) 

F:>
FullyConnectedTensorProduct(1x1o x 1x1o -> 1x0e+1x1e+1x2e | 3 paths | 3 weights)
Finv:>
FullyConnectedTensorProduct(1x0e+1x1e+1x2e x 1x0e+1x1e+1x2e -> 1x1o | 0 paths | 0 weights)

```

So just the fact that there are no reversible path to the above operation I guess rules out the posibility of the tensorproduct being its own inverse operation, but is there any other operation that might be the tensorproducts inverse operation?

**Comment by mariogeiger** [comment]
Try this
```python
irreps_x = o3.Irreps('1o')
irreps_z = o3.Irreps('4x1o')

tp = o3.FullTensorProduct(irreps_x, irreps_z, ['0e'])
print(tp)

irreps_y = tp.irreps_out

z = irreps_z.randn(-1)

M = tp.right(z)
print(M.shape)

# forward
x = irreps_x.randn(-1)
y = x @ M

# inverse
invM = torch.pinverse(M)
x2 = y @ invM

assert torch.allclose(x, x2)
```

Note that the choice of `irreps_z` is critical, for instance 3 vectors still works but 2 is not enough, simply because they would not form a complete basis of `R^3`.
Also note that some special values of `z` will not lead to an invertible matrix.

You can do the same with more complex irreps
```python
irreps_x = o3.Irreps('0e + 1o + 2e')
irreps_z = o3.Irreps('2x1o')

tp = o3.FullTensorProduct(irreps_x, irreps_z, ['0e', '0o', '1e', '1o'])
print(tp)  # FullTensorProduct(1x0e+1x1o+1x2e x 2x1o -> 2x0e+4x1o+2x1e | 8 paths | 0 weights)

irreps_y = tp.irreps_out

z = irreps_z.randn(-1)

M = tp.right(z)
print(M.shape)  # torch.Size([9, 20])

# forward
x = irreps_x.randn(-1)
y = x @ M

# inverse
invM = torch.pinverse(M)
x2 = y @ invM

assert torch.allclose(x, x2)
```

**Comment by tueboesen** [comment]
@mariogeiger That is really cool, I should look more into the tp.right, which I have definitely just skipped over everytime I encountered it so far. 
Though the pinverse will probably prevent this from actually being useful for any realistic network. 
For simpler non-equivariant networks I have been using trainable semi unitary matrices to do projection/uplifting which enables quite a lot of cool possibilities when it comes to constraints, I was curious to see whether I could do similar stuff directly with tensorproducts.

Anyway you have once again given me lots to think about, so thank you very much!
