### ISSUE TITLE
Performance of python-based KernelFn

### ISSUE THREAD

**Issue by bkmi** [e3nn/e3nn#28]
I have compared using KernelFn (forwards and backwards in python) to using the automatic differentiation available by only coding the forward pass. The file I used to prepare the test is written here.

```python
import torch

from e3nn.kernel import Kernel, KernelAutoBackward
from e3nn.radial import ConstantRadialModel


torch.set_default_dtype(torch.float64)
device = torch.device('cuda')

Rs_in = [(1, 0), (1, 1), (2, 0), (1, 2)]
Rs_out = [(2, 0), (1, 1), (1, 2), (3, 0)]
batch = 100
atoms = 40

k = Kernel(Rs_in, Rs_out, RadialModel=ConstantRadialModel).to(device)
kab = KernelAutoBackward(Rs_in, Rs_out, RadialModel=ConstantRadialModel).to(device)


def forward_backward(kernel):
    geometry = torch.rand(batch, atoms, 3).to(device)
    features = kernel(geometry)
    target = torch.rand_like(features).to(device)
    loss = torch.norm(features - target)
    loss.backward()
```

When using ```device = torch.device('cuda')``` I got the following results for speed:
```ipython
In [1]: %timeit -n15 -r70 forward_backward(k)                                                                                                            
20.5 ms ± 575 µs per loop (mean ± std. dev. of 70 runs, 15 loops each)

In [2]: %timeit -n15 -r70 forward_backward(kab)                                                                                                          
22.7 ms ± 273 µs per loop (mean ± std. dev. of 70 runs, 15 loops each)
```
and cuda memory results were custom written by me comparing the max allocated memory before and after running the function.
```ipython
In [1]: forward_backward(k)                                                                                                                              
allocated 19.730432 MB
cached 25.165824 MB

In [2]: forward_backward(kab)                                                                                                                            
allocated 30.536704 MB
cached 31.45728 MB
```

Now, when I used ```device = torch.device('cpu')```, I got the following results for speed:
```ipython
In [1]: %timeit forward_backward(k)                                                                                                                      
207 ms ± 2.08 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)

In [2]: %timeit forward_backward(kab)                                                                                                                    
237 ms ± 1.82 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
and for memory
```ipython
In [1]: %memit forward_backward(k)                                                                                                                       
peak memory: 220.74 MiB, increment: 33.52 MiB

In [2]: %memit forward_backward(kab)                                                                                                                     
peak memory: 275.71 MiB, increment: 56.20 MiB
```

--

I think the memory and speed usage implies that we should simply use the built-in/automatic differentiation rather than actually coding our own forward and backward functions. However keeping them in the code base might be useful since effort was made to write down the explicit derivative. If we ever convert the kernel to a cuda call it might be useful to have that code around. (also to compare to)

**Comment by mariogeiger** [comment]
Very nice that you did the test 👌

**Comment by bkmi** [comment]
The default behavior is to use custom backward for KernelConv and the automatic backward for kernel and convolution.

When using KernelConv with custom_backward=True in qm9 I was able to do 1000 molecule epochs in 11 seconds. When using custom_backward=False in qm9 the same number of molecules were iterated over in nearly 18 seconds.

It seems the behavior of these functions depends on the context. I believe it calls for further study whether or not custom_backward for Kernel should be enabled by default.
