### ISSUE TITLE
Partial derivatives of spherical harmonics with respect to polar and azimuthal angles❓ [QUESTION]

### ISSUE THREAD

**Issue by siddanib** [e3nn/e3nn#281]
Hello,

I am using e3nn code as part of my project, and I am now required to also implement partial derivatives of spherical harmonics with respect to polar and azimuthal angles as part of this project. Could you please give me some suggestions on how I can use some of the existing classes to implement the partial derivatives.

Thank you very much for making this code publicly available!!
Regards,
Bhargav

**Comment by mariogeiger** [comment]
```python
from functools import partial
import torch
from e3nn import o3

torch.autograd.functional.jacobian(
    partial(o3.spherical_harmonics_alpha_beta, 2), 
    (torch.tensor(0.2), torch.tensor(0.1))
)
```

**Comment by mariogeiger** [comment]
Your definition of theta and phi looks correct, it's the same as in
https://github.com/e3nn/e3nn/blob/main/e3nn/o3/_rotation.py#L684-L685

For the rest I can't tell like that if it's correct or not, but I unfortunately don't have the time to investigate it now

**Comment by siddanib** [comment]
Hello Mario,

Thank you very much for giving me the inputs. After cross-verify my Spherical Harmonics with those of "o3.spherical_harmonics_alpha_beta", I understood that the spherical harmonics are being implemented as follows.

![Spherical_harmonics](https://user-images.githubusercontent.com/45137944/121267556-60ccab00-c88a-11eb-859e-9e9adf6cf813.PNG)

This resolved the equivariance issue that I was facing earlier.

Warmest regards,
Bhargav
