### ISSUE TITLE
🐛 [BUG] FullyConnectedNet is not compatible with DataParallel

### ISSUE THREAD

**Issue by Karbo123** [e3nn/e3nn#283]
**Describe the bug**
`FullyConnectedNet` is not compatible with `DataParallel`, as the codes of `FullyConnectedNet` contains the use of `ParameterList`. However, `ParameterList` is not recommended to work with `DataParallel` (see: [nn.Parameter{List,Dict} not copied to gpus in forward pass when nn.DataParallel is used](https://github.com/pytorch/pytorch/issues/36035)).
But there is a workaround, we can use `register_parameter` instead.
For example, modify [line34](https://github.com/e3nn/e3nn/blob/main/e3nn/nn/_fc.py#L34) to
``` python
self.register_parameter(f"weight_{i}", torch.nn.Parameter(torch.randn(h1, h2)))
```
and then modify other codes accordingly.

**To Reproduce**
First type: `CUDA_VISIBLE_DEVICES=6,7 ipython` # using 2 cards
``` python
import torch
from torch.nn import DataParallel
from e3nn.nn import FullyConnectedNet
fc = DataParallel(FullyConnectedNet([10, 20, 30]).cuda())
y = fc(torch.randn(32, 10).cuda())
y.sum().backward() # it will raise an error
```

**Expected behavior**
There should be no error when backpropagating.

**Environment (please complete the following information):**
- OS: Ubuntu
- python: 3.7.10
- e3nn: 0.3.1 (c05c2a7)
- pytorch: 1.8.0+cu101
- pytorch_geometric: 1.6.3

**Comment by mariogeiger** [comment]
Thanks, I just fixed it in https://github.com/e3nn/e3nn/commit/36eddb19d6c5b07eb82efea685b4da42d840cf5c
