### ISSUE TITLE
❓ [QUESTION] How exactly does the FullyConnectedTensorProduct work?

### ISSUE THREAD

**Issue by iorin0217** [e3nn/e3nn#284]
I'm confusing about learnable weights implemented in `FullyConnectedTensorProduct`.
For example
```
tp = FullyConnectedTensorProduct(irreps_in1="1x0e",irreps_in2="2x0e",irreps_out="1x0e")
w = list(tp.weight_views())[0]
x = o3.Irreps("1x0e").randn(-1)
y = o3.Irreps("2x0e").randn(-1)
```
The values are
```
w: tensor([[[-0.0048],
         [-2.1463]]], grad_fn=<ViewBackward>)
x: tensor([0.7021])
y: tensor([-0.9132,  0.8710])
tp(x,y): tensor([-0.9259], grad_fn=<ViewBackward>)
w[0][0]*x[0]*y[0]+w[0][1]*x[0]*y[1]: tensor([-1.3094], grad_fn=<AddBackward0>)
```
Why `tp(x,y)` is not equals to `w[0][0]*x[0]*y[0]+w[0][1]*x[0]*y[1] `?

**Comment by mariogeiger** [comment]
Because there is a normalization constant. Here it will be 1/sqrt(2). 

Normalization scheme:
1. inputs have mean(x**2)=1
2. each output is mean 0 and variance 1 (expectation over the weights distribution)
3. each weight is sampled from a normal gaussian (mean 0 and variance 1)

=> multiplicative constants are added to enforce point 2

**Comment by iorin0217** [comment]
Thank you for your polite response.
I also understand why there are input options such as `in1_var`.

By the way, I have another question about Clebsch–Gordan coefficients.
1. I have compared `o3.wigner_3j` with the `Wigner3j` implemented in `Sympy` ([https://docs.sympy.org/latest/modules/physics/quantum/cg.html](https://docs.sympy.org/latest/modules/physics/quantum/cg.html)), and these values do not match. What's going on here?

```python
from sympy.physics.quantum.cg import Wigner3j
o3.wigner_3j(1,2,3)
'''
tensor([[[-0.0000, -0.0000, -0.0000, -0.0000, -0.0690, -0.0000, -0.2673],
         [-0.0000, -0.0000, -0.0000, -0.1690, -0.0000, -0.2182, -0.0000],
         [-0.0000, -0.0000,  0.2390, -0.0000, -0.0000, -0.0000, -0.0000],
         [-0.0000,  0.2182, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000],
         [ 0.2673, -0.0000,  0.0690, -0.0000, -0.0000, -0.0000, -0.0000]],

        [[-0.0000,  0.2182, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000],
         [-0.0000, -0.0000,  0.2760, -0.0000, -0.0000, -0.0000, -0.0000],
         [-0.0000, -0.0000, -0.0000,  0.2928, -0.0000, -0.0000, -0.0000],
         [-0.0000, -0.0000, -0.0000, -0.0000,  0.2760, -0.0000, -0.0000],
         [-0.0000, -0.0000, -0.0000, -0.0000, -0.0000,  0.2182, -0.0000]],

        [[ 0.2673, -0.0000, -0.0690, -0.0000, -0.0000, -0.0000, -0.0000],
         [-0.0000,  0.2182, -0.0000, -0.0000, -0.0000, -0.0000, -0.0000],
         [-0.0000, -0.0000, -0.0000, -0.0000,  0.2390, -0.0000, -0.0000],
         [-0.0000, -0.0000, -0.0000, -0.1690, -0.0000,  0.2182, -0.0000],
         [-0.0000, -0.0000, -0.0000, -0.0000, -0.0690, -0.0000,  0.2673]]])
'''
w3j = Wigner3j(1,0,2,0,3,0)
w3j.doit() # -0.2927700218845599
w3j = Wigner3j(1,-1,2,-1,3,2)
w3j.doit() # -0.3086066999241838
w3j = Wigner3j(1,0,2,-2,3,2)
w3j.doit() # -0.21821789023599236
w3j = Wigner3j(1,-1,2,-2,3,3)
w3j.doit() # 0.37796447300922725
```

2. Does the `m` index of `Y_{lm}` correspond to the index of `o3.wigner_3j`? For example, `o3.wigner_3j(1,2,3)[0,2,6]` means `(l,m) = (1,-1), (2,0), (3,3)`?

3. Sorry if I'm wrong, why using Wigner 3j instead of Clebsch–Gordan coefficients to calculate Tensor Products?

**Comment by mariogeiger** [comment]
We don't use the same irreps as sympy. there is a change of basis (for each l) between our irreps and sympy irreps. They have complex irreps and we have a real one. 

Wigner 3j and Clebsh Gordan are the same up to a constant (constant that depends on the l's).
