### ISSUE TITLE
bugs and confusion in radial model

### ISSUE THREAD

**Issue by bkmi** [e3nn/e3nn#31]
I'm fairly sure [line 37](https://github.com/e3nn/e3nn/blob/master/e3nn/radial.py#L37) is a bug
```
diff = x.unsqueeze(1) - self.position.unsqueeze(0)  # [batch, i, ...]
batch, n, *rest = diff.size()
x = self.basis(diff.view(-1, *rest)).view(batch, n)  # [batch, i]
return self.f(x)
```
since it will raise an error when rest is anything by an empty list.

The cosine basis needs some clarification. 
Am I right in determining that its mathematical formula is

```
\begin{cases}
  cos^2 (\gamma (d_{ab} - \mu_{k}) \frac{\pi}{2}) & 1 \geq \gamma (d_{ab} - \mu_{k}) \geq -1 \\
  0 & otherwise
\end{cases}
```
![CodeCogsEqn(1)](https://user-images.githubusercontent.com/12955549/76419722-1f0c3680-63a1-11ea-9bcf-b974b3010844.gif)

**Comment by mariogeiger** [comment]
What do you mean by "anything by an empty list"?

The formula looks good

**Comment by bkmi** [comment]
You cannot pass anything but a flat vector to `FiniteElementModel.forward`. I.e. rest has to be nothing.

--

Okay, I think I'll add that to the documentation just so it's a bit clearer.

**Comment by mariogeiger** [comment]
There is no bugs, if it crash it's because `self.basis` does not support `rest` to be different that empty list. It is written in case you have a `self.basis` function from `R^d -> R`.

**Comment by blondegeek** [comment]
@bkmi @mariogeiger I'm cleaning up issues. Should I keep this open or close it?

**Comment by mariogeiger** [comment]
For me you can close

**Comment by bkmi** [comment]
I still don't understand to be honest but it's okay. I vote close.
