### ISSUE TITLE
🐛 [BUG]

### ISSUE THREAD

**Issue by lx19930** [e3nn/e3nn#311]
**Describe the bug**
I am trying to go through the code you provided and something goes south. The attempt to perform a tensor product failed.
( I am copying the codes in https://docs.e3nn.org/en/stable/guide/convolution.html to my own environment and run them.

**To Reproduce**
import torch
from torch_cluster import radius_graph
from torch_scatter import scatter
from e3nn import o3, nn
from e3nn.math import soft_one_hot_linspace
import matplotlib.pyplot as plt
irreps_input = o3.Irreps("10x0e + 10x1e")
irreps_output = o3.Irreps("20x0e + 10x1e")
num_nodes = 100
pos = torch.randn(num_nodes, 3)  # random node positions
# create edges
max_radius = 1.8
edge_src, edge_dst = radius_graph(pos, max_radius, max_num_neighbors=num_nodes - 1)
print(edge_src.shape)
edge_vec = pos[edge_dst] - pos[edge_src]
# compute z
num_neighbors = len(edge_src) / num_nodes
num_neighbors
f_in = irreps_input.randn(num_nodes, -1)
print(f_in.pow(2).mean())
irreps_sh = o3.Irreps.spherical_harmonics(lmax=2)
print(irreps_sh)
sh = o3.spherical_harmonics(irreps_sh, edge_vec, normalize=True, normalization='component')
# normalize=True ensure that x is divided by |x| before computing the sh
print(sh.pow(2).mean())  # should be close to 1
tp = o3.FullyConnectedTensorProduct(irreps_input, irreps_sh, irreps_output, shared_weights=False)

**Expected behavior**
I expected it to run successfully

**Environment (please complete the following information):**
 - OS: Unix
 - python version (`python --version`) 3.8
 - python environment (commands are given for python interpreter):
   - e3nn version (`import e3nn; e3nn.__version__`) 0.4.0
   - pytorch version (`import torch; torch.__version__`)  1.10.0+cu102
   - pytorch_geometric version (`import torch_geometric; torch_geometric.__version__`)  2.0.2
 - (if relevant) GPU support with CUDA
   -  cuda Version according to nvcc (`nvcc --version`) 10.2
   -  cuda version according to pyTorch (`import torch; torch.version.cuda`) 10.2

**Screenshots**

**Additional context**
the error message is
  File "conv.py", line 32, in <module>
    tp = o3.FullyConnectedTensorProduct(irreps_input, irreps_sh, irreps_output, shared_weights=False)
  File "/projects/academic/wjzheng/xliu79/anaconda3/envs/e3nn_torch/lib/python3.8/site-packages/e3nn/o3/_tensor_product/_tensor_product.py", line 724, in __init__
    super().__init__(irreps_in1, irreps_in2, irreps_out, instr, **kwargs)
  File "/projects/academic/wjzheng/xliu79/anaconda3/envs/e3nn_torch/lib/python3.8/site-packages/e3nn/o3/_tensor_product/_tensor_product.py", line 260, in __init__
    graphmod_out, graphmod_right = codegen_tensor_product(
  File "/projects/academic/wjzheng/xliu79/anaconda3/envs/e3nn_torch/lib/python3.8/site-packages/e3nn/o3/_tensor_product/_codegen.py", line 192, in codegen_tensor_product
    xx_dict[key] = torch.einsum('zui,zvj->zuvij', x1_out, x2_out)
  File "/projects/academic/wjzheng/xliu79/anaconda3/envs/e3nn_torch/lib/python3.8/site-packages/torch/functional.py", line 318, in einsum
    return handle_torch_function(einsum, operands, equation, *operands)
  File "/projects/academic/wjzheng/xliu79/anaconda3/envs/e3nn_torch/lib/python3.8/site-packages/torch/overrides.py", line 1355, in handle_torch_function
    result = torch_func_method(public_api, types, args, kwargs)
  File "/projects/academic/wjzheng/xliu79/anaconda3/envs/e3nn_torch/lib/python3.8/site-packages/torch/fx/proxy.py", line 276, in __torch_function__
    raise RuntimeError(f'Found multiple different tracers {list(tracers.keys())} while '
RuntimeError: Found multiple different tracers [<torch.fx.proxy.GraphAppendingTracer object at 0x7f5c75291a30>, <torch.fx.proxy.GraphAppendingTracer object at 0x7f5c75291a60>] while trying to trace operations <function einsum at 0x7f5cc5abb670>

**Comment by mariogeiger** [comment]
Try to upgrade to e3nn=0.4.1 and opt_einsum_fx=0.1.3
I guess thes error were introduced by the last version of pytorch=1.10

**Comment by lx19930** [comment]
> Try to upgrade to e3nn=0.4.1 and opt_einsum_fx=0.1.3 I guess thes error were introduced by the last version of pytorch=1.10

It worked, thank you so much!
