### ISSUE TITLE
🐛 [BUG] device of change of basis matrix in CartesianTensor

### ISSUE THREAD

**Issue by mjwen** [e3nn/e3nn#316]
[CartesianTensor](https://github.com/e3nn/e3nn/blob/34ebae91b094392a9f26dfa153f9350d0e24d185/e3nn/io/_cartesian_tensor.py#L4) is not a subclass of torch Module, and thus when a model contains it as an attribute is moved to gpu, [rtp](https://github.com/e3nn/e3nn/blob/34ebae91b094392a9f26dfa153f9350d0e24d185/e3nn/io/_cartesian_tensor.py#L44) will not be moved to gpu. Then calling [from_cartesian()](https://github.com/e3nn/e3nn/blob/34ebae91b094392a9f26dfa153f9350d0e24d185/e3nn/io/_cartesian_tensor.py#L51) with `data` on gpu will cause problem. 

Of course, since it is not a torch Module, we probably should not use it as a model attribute. But assume this is fine, how do we want to fix it? 

The easiest way is to let `Q -> Q.to(data.device)` in `from_cartesian()` and `to_cartesian()`, but this will do the data transfer each time it is called. Alternative, we can make the class a torch Module, but it looks this does not follow its designing pattern. 

Any suggestions?

**Comment by mariogeiger** [comment]
That is not a trivial problem to fix.

I propose this solution: https://github.com/e3nn/e3nn/pull/320
Tell me what you think @mjwen @blondegeek

**Comment by mjwen** [comment]
Fixed by #320; closing it.
