### ISSUE TITLE
Qestion About the activation

### ISSUE THREAD

**Issue by xuyinxuyin** [e3nn/e3nn#330]
Hi, thanks for sharing this great project and your effort.
I'm doing researches on closely relevant topics of equivariance, and I'm a bit curious which papers correspond to the following activations:
- The activation on S2 seems to be equivalent to a recent CVPR paper: https://openaccess.thecvf.com/content/CVPR2021/papers/Poulenard_A_Functional_Approach_to_Rotation_Equivariant_Non-Linearities_for_Tensor_Field_CVPR_2021_paper.pdf

   https://github.com/e3nn/e3nn/blob/bd873a1cfcbad36c2ac233e9e48d7b7c3c5892f4/e3nn/nn/_s2act.py#L9

- Could you help to refer to the original publication about this SO(3) activation?
https://github.com/e3nn/e3nn/blob/5c0d2fdcc719190e40a887ddb5bd5790e196ba5f/e3nn/nn/_so3act.py#L8

Thanks!

**Comment by mariogeiger** [comment]
`SO3Activation` comes directly from https://openreview.net/pdf?id=Hkbd5xZRb (FT + activation + FT) and `S2Activation` is inspired from it (unpublished work)

The paper you cite indeed does it as well but I was not aware of its existence.
