### ISSUE TITLE
lie_learn error when calling o3.irr_repr

### ISSUE THREAD

**Issue by JoshRackers** [e3nn/e3nn#34]
When I call o3.irr_repr, I get this error associate with lie_learn trying to grab Wigner D matrix. 

`---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
~/anaconda3/envs/e3nn/lib/python3.8/site-packages/numpy/lib/npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    459             try:
--> 460                 return pickle.load(fid, **pickle_kwargs)
    461             except Exception:

EOFError: Ran out of input

During handling of the above exception, another exception occurred:

OSError                                   Traceback (most recent call last)
<ipython-input-18-bd1bab1731bf> in <module>
     11 
     12 # Wigner D matrix -- rotation matrix for irreducible representations
---> 13 wignerD = o3.direct_sum(*[o3.irr_repr(l, *angles) for mul, l, parity in Rs_3x3 for _ in range(mul)])
     14 print("Shape of Wigner-D matrix:", wignerD.shape)
     15 

<ipython-input-18-bd1bab1731bf> in <listcomp>(.0)
     11 
     12 # Wigner D matrix -- rotation matrix for irreducible representations
---> 13 wignerD = o3.direct_sum(*[o3.irr_repr(l, *angles) for mul, l, parity in Rs_3x3 for _ in range(mul)])
     14 print("Shape of Wigner-D matrix:", wignerD.shape)
     15 

~/anaconda3/envs/e3nn/lib/python3.8/site-packages/e3nn/o3.py in irr_repr(order, alpha, beta, gamma, dtype, device)
    142     - compatible with compose and spherical_harmonics
    143     """
--> 144     from lie_learn.representations.SO3.wigner_d import wigner_D_matrix
    145     abc = [alpha, beta, gamma]
    146     for i, x in enumerate(abc):

~/anaconda3/envs/e3nn/lib/python3.8/site-packages/lie_learn/representations/SO3/wigner_d.py in <module>
      2 import numpy as np
      3 
----> 4 from lie_learn.representations.SO3.pinchon_hoggan.pinchon_hoggan_dense import Jd, rot_mat
      5 from lie_learn.representations.SO3.irrep_bases import change_of_basis_matrix
      6 

~/anaconda3/envs/e3nn/lib/python3.8/site-packages/lie_learn/representations/SO3/pinchon_hoggan/pinchon_hoggan_dense.py in <module>
     15 # https://iopscience.iop.org/article/10.1088/1751-8113/40/7/011/
     16 
---> 17 Jd = download('https://github.com/AMLab-Amsterdam/lie_learn/releases/download/v1.0/J_dense_0-278.npy')
     18 
     19 def SO3_irreps(g, irreps):

~/anaconda3/envs/e3nn/lib/python3.8/site-packages/lie_learn/representations/SO3/pinchon_hoggan/download.py in download(url)
      9     if not os.path.isfile(path):
     10         open(path, 'wb').write(requests.get(url).content)
---> 11     return np.load(path, encoding='latin1', allow_pickle=True)

~/anaconda3/envs/e3nn/lib/python3.8/site-packages/numpy/lib/npyio.py in load(file, mmap_mode, allow_pickle, fix_imports, encoding)
    460                 return pickle.load(fid, **pickle_kwargs)
    461             except Exception:
--> 462                 raise IOError(
    463                     "Failed to interpret file %s as a pickle" % repr(file))
    464     finally:

OSError: Failed to interpret file '/Users/jracker/anaconda3/envs/e3nn/lib/python3.8/site-packages/lie_learn/representations/SO3/pinchon_hoggan/J_dense_0-278.npy' as a pickle`

**Comment by mariogeiger** [comment]
Failed to interpret file `/Users/jracker/anaconda3/envs/e3nn/lib/python3.8/site-packages/lie_learn/representations/SO3/pinchon_hoggan/J_dense_0-278.npy` as a pickle

It’s not the first time there is a problem for loading this pickle file, it might be that some versions of numpy have problems loading it. 
I will try to load it and save it again. Maybe it was saved with an old version of numpy which causes the problem.

**Comment by JoshRackers** [comment]
Thanks for helping with this! It is odd because I have what I think are identical installing installations of lie_learn in two different conda environments (one for se3cnn and one for e3nn) and the other one (se3cnn) does not give this error.

**Comment by mariogeiger** [comment]
Funny. it's maybe due to the versions of numpy in the two env. I recreated the npy file and uploaded it at the same url. Can you try to remove `/Users/jracker/anaconda3/envs/e3nn/lib/python3.8/site-packages/lie_learn/representations/SO3/pinchon_hoggan/J_dense_0-278.npy` and execute `o3.irr_repr` again plz.

**Comment by JoshRackers** [comment]
That did it! Thanks

**Comment by mariogeiger** [comment]
Cool
