### ISSUE TITLE
reduce_tensor_product vs. tensor_product

### ISSUE THREAD

**Issue by JoshRackers** [e3nn/e3nn#35]
In the switch from se3cnn to e3nn, it looks like the function reduce_tensor_product was moved to the new rs.py file and renamed tensor_product. However, the two do not give the same output for identical input. I have tried every permutation of indices and sign flips and cannot get the outputs to equal each other. Has the functionality changed or is there something I'm missing here?

**Comment by mariogeiger** [comment]
I think the order of the indices changed.
https://github.com/e3nn/e3nn/commit/a0828558958793ae31d549778cddbbbb550c8f71#diff-696428c25b06b0a30d93945e7dc84262R483
it was [input1, input2, output]

and now it is [output, input1, input2]

**Comment by JoshRackers** [comment]
I've tried that permutation, but the returned clebsch_gordan_tensor does not match the old code. Let me get a minimal example really quick and I'll post it.

**Comment by JoshRackers** [comment]
Using se3cnn:
```python
import se3cnn.SO3 as SO3
Rs_vec = [(1, 1)] # Representation list of a single vector
Rs_3x3, C = SO3.reduce_tensor_product(Rs_vec, Rs_vec) # Rep vec and Clebsch-Gordon

print(C.shape)
print(C[0,0,:])
```
output:
```
torch.Size([3, 3, 9])
tensor([ 5.7735e-01,  2.7413e-18,  2.4537e-17,  5.6656e-17,  6.0050e-17,
         1.6422e-16, -4.0825e-01, -1.9247e-16, -7.0711e-01],
       dtype=torch.float64)
```

Using e3nn:
```python
from e3nn.rs import tensor_product
Rs_vec = [(1, 1)] # Representation list of a single vector
Rs_3x3, C = tensor_product(Rs_vec, Rs_vec) # Rep vec and Clebsch-Gordon

print(C.shape)
print(C[:,0,0])
```
output:
```
torch.Size([9, 3, 3])
tensor([ 5.7735e-01,  3.5655e-19, -1.1404e-16, -4.7356e-17,  3.7950e-17,
         2.6705e-16,  4.0825e-01,  1.1973e-18,  7.0711e-01])
```

There's some funny sign thing going on that I don't understand.

**Comment by mariogeiger** [comment]
If it’s just a matter of sign it’s probably simply because we changed the convention to fix the sign of the CG coefficients. You can check if the CG changed from se3cnn to e3nn. Note the CG does the job independently of its sign

**Comment by JoshRackers** [comment]
The sign change isn't global, though, so I'm not sure what the convention change was. For example C[0,0,0] = 5.7735e-01 in both, but C[8,0,0] (C[0,0,8]) is positive in one, but negative in the other.

**Comment by mariogeiger** [comment]
Are you comparing the output of `tensor_product` or `clebsch_gordan` function ?

**Comment by JoshRackers** [comment]
tensor_product

I think all is okay here. Using the CG coefficients gives the same results.

**Comment by mariogeiger** [comment]
Is it clear for you now or it there still something weird for you?

**Comment by JoshRackers** [comment]
I think all is good. I was talking to @blondegeek about this and it looks like it really is just a change in the selected convention. My few tests show that it works the same as before, so we can go ahead and close this.
