### ISSUE TITLE
❓ Can't intall e3nn.point

### ISSUE THREAD

**Issue by Antioxidant233** [e3nn/e3nn#361]
Hello! I installed the e3nn package through command`pip install --upgrade e3nn`, and it successfully installed the package. However, e3nn.point cannot be found as shown in the picture. Has anybody encountered the same problem?
The code for accessing e3nn.point and the warning is as below:
```
import e3nn.point.data_helpers as dh
ModuleNotFoundError: No module named 'e3nn.point'
```
Thank you very much!

**Comment by Antioxidant233** [comment]
nvm solved.

**Comment by yuehua-Song666** [comment]
Hi,

Sorry for disturbing you. I got the same problem. Can you please tell me exactly how to solve the problem?

Thanks,
Yuehua
