### ISSUE TITLE
❓ [QUESTION] How does even/odd parity connect to Clebsch-Gordan Coefficient?

### ISSUE THREAD

**Issue by luwei0917** [e3nn/e3nn#367]
I want to understand what is under the hood of the TensorProduct function.
Here is my code:
```
import torch
from e3nn import o3
import numpy as np

torch.manual_seed(0)
irreps_in1 = o3.Irreps('1o')
irreps_in2 = o3.Irreps('1e')
irreps_out = o3.Irreps('2o')

tp = o3.FullyConnectedTensorProduct(irreps_in1 , irreps_in2 , irreps_out )

tp.weight = torch.nn.Parameter(torch.tensor([1.0]))
x1 = torch.tensor ([1, 1, 3])
x2 = torch.tensor ([4.1, 1, 2])
out = tp(x1 , x2) # evaluate the tensor product
out


```
The out I got is 
10.1116,  3.6062, -3.3068,  3.5355,  1.3435

I want to know how these values are computed. 
I think we need the Clebsch-Gordan table, but I don't know how the j,m is connected to the even/odd ('e', 'o') we specified. 
 
Thanks!

**Comment by mariogeiger** [comment]
The contribution of the parity (even and odd) to the Clebsch-Gordan coefficients is super simple:
If the triplet of irreps is `(e,e,e)`, `(e,o,o)`, `(o,e,o)` or `(o,o,e)` then the Clebsch-Gordan are the same.
Otherwise, the Clebsch-Gordan are zero.
