### ISSUE TITLE
Confusion about the different fromulation of sperical harmonics function in wiki and implementation

### ISSUE THREAD

**Issue by Oceanusity** [e3nn/e3nn#369]
Hi, 

From the wiki, when `l=2`, the real spherical harmonics function is shown like:
![image](https://user-images.githubusercontent.com/36795878/196296845-753d3e4a-111d-48eb-a362-f29bb5631c9e.png)

But in the [implementation](https://github.com/e3nn/e3nn/blob/41c184cc4b782dd6215e9054a8c5ffa9ebe7fb92/e3nn/o3/_spherical_harmonics.py#L200), the function is written like this:
![image](https://user-images.githubusercontent.com/36795878/196297112-2f6770c5-d1a6-4fd7-912f-a0c7e90f7cbd.png)

I am confused about whether these two have the same meaning. Especially, `Y_2^0 = 3z^2 -1` in wiki, while it is `Y_2^0 = y^2 - 0.5 * (x^2 + z^2)` in the implementation.

Thank you for your help, and welcome to give me some guidance.

**Comment by mariogeiger** [comment]
Hi,

`y^2 - 0.5 * (x^2 + z^2) = 1.5 * y^2 - 0.5 * (x^2 + y^2 + z^2) = 0.5 * (3 * y^2 - r^2)`

`y` in e3nn correspond to `z` in wikipedia.
