### ISSUE TITLE
flake8 test

### ISSUE THREAD

**Issue by mariogeiger** [e3nn/e3nn#37]
flake8 is passing although there is errors

![https://github.com/e3nn/e3nn/runs/520374735](https://user-images.githubusercontent.com/333780/77159653-0c32e980-6aa6-11ea-8340-cccf58136b9f.png)

https://github.com/e3nn/e3nn/runs/520374735

**Comment by bkmi** [comment]
Ah, weird. I'll take a look.

**Comment by mariogeiger** [comment]
fixed in 4e0e4d62a0bdb16a7f9af1b45f1b2c0f27421fb7
