### ISSUE TITLE
🌟 [FEATURE] The C-G coefficients inside

### ISSUE THREAD

**Issue by Fadelis98** [e3nn/e3nn#372]
**Is your feature request related to a problem? Please describe.**

I want to deal with a rank 2 matrix whose elements are $\left<\psi_i\right|\hat{A}\left|\psi_j\right>$(in dirac notation).  So it transforms as a rank-2 tensor with basis set $\left<\psi_i\right|\otimes\left|\psi_j\right>$, which is not the basis of direct sum of irreps.

However, in e3nn, all the `Tensorproduct` can only output the decomposed form, for example ` '1e x 1e'-->'0e+1e+5e' `, without giving the C-G coefficients to transform back and forth.

I didn't find out the code related to the coefficients, but I think that the code should have calculated it inside. It's more convenient and efficient is e3nn can provide it to avoid extra computation.

**Describe the solution you'd like**

Either to store the cg coefficients explicitly or to output the direct product form optionally
e.g.
``` python
x = torch.tensor([1,0,0])
y = torch.tensor([0,1,0])
tb = o3.FullTensorProduct('1e','1e')
decomposed_form = tb(a,b) 
# current result is :
# tensor([ 0.0000,  0.0000,  0.0000, -0.7071,  0.0000,  0.7071,  0.0000,  0.0000, 0.0000])
# what I want is (ignore dtype here):
# origin_form =  tensor([0,1,0,0,0,0,0,0,0])
```
one way is to store the cg coefficients:

``` python
tb.cg : Tensor  # a tensor that satisfy  decomposed_form = matmul(cg,nature_form)
```

**Describe alternatives you've considered**

Another way is add an option to the forward call of tensorproduct:

```python
origin_form = tb(x,y,decompose = False)
decomposed_form = tb(x,y)
```

**Additional context**

**Comment by mariogeiger** [comment]
Did you consider doing:

```python
origin_form  = torch.einsum("i,j->ij", x, y)
```

Then to obtain the CG using this class https://github.com/e3nn/e3nn/blob/main/e3nn/o3/_reduce.py#L80 and change basis to reduce:

```python
tb_cg = ReducedTensorProducts("ij", i="1e", j="1e").change_of_basis

decomposed_form  = torch.einsum("kij,ij", tb_cg, origin_form)
```

**Comment by Fadelis98** [comment]
@mariogeiger that's exactly what I need, thanks!
