### ISSUE TITLE
🌟 [FEATURE] `FullyConnectedTensorProduct` with symmetric weights.

### ISSUE THREAD

**Issue by pfebrer** [e3nn/e3nn#412]
**Is your feature request related to a problem? Please describe.**
In our model we were puzzled by a bug where a scalar output of a tensor product (`tp`) of two inputs (`x`, `y`) depended on whether we did `tp(x, y)` or `tp(y, x)`, because for our application it shouldn't matter. After thinking about it, we discovered that it was to be expected, since this was a `FullyConnectedTensorProduct`. This is a sketch I made to understand our problem:

![IMG_20230803_141304](https://github.com/e3nn/e3nn/assets/42074085/897e228a-25c7-4bd3-a50b-17e2fe808903)

Having a scalar output that needs to satisfy commutability of the inputs is just a simplification of our case to understand what we were doing wrong and in fact what we want is that if we do `3x1o [x] 3x1o = 3x1e` we can commute the input factors and get the same behavior as if we did `1x1o [x] 1x1o = 1x1e`. For the l=1 case for example if we commute the input factors we would expect all the `1e` outputs to be the same vector with opposite sign. So in general, what we need is a way of imposing symmetry in the weights on a `FullyConnectedTensorProduct` I.e.:

![IMG_20230803_152215](https://github.com/e3nn/e3nn/assets/42074085/773ef1c0-68ef-433b-9e75-89c6b8598eed)

**Describe the solution you'd like**
If this tensor product is useful enough, it would be very nice to have a dedicated tensor product class for it or a `symmetric_weights` argument in the `FullyConnectedTensorProduct`.

If not, we would really appreciate some advice on how it would be possible to acheive something like this, maybe using `instructions` (?).

**Describe alternatives you've considered**
For our particular case we can symmetrize the output by doing `f(x, y) + f(y, x)` with some additional processing, but it seems like a waste of computation and also there are more trainable parameters than real "degrees of freedom".

**Comment by mariogeiger** [comment]
Hi, you should use ReducedTensorProducts followed with a Linear (for the weights). 


https://docs.e3nn.org/en/latest/api/o3/o3_reduce.html

**Comment by pfebrer** [comment]
Hi, thank you! 

I get the idea of tensor product + linear, but why `ReducedTensorProducts` and not `FullTensorProduct`?

(I see now that this should be a discussion instead of an issue)

**Comment by mariogeiger** [comment]
Because you can impose the symmetry

**Comment by pfebrer** [comment]
But as I understand it, the symmetry that you pass to `ReducedTensorProducts` is a symmetry between inputs, isn't it? I don't have any symmetry between inputs.

This is a comparison between what I think we need vs what the reduced tensor product does if you impose ij=ji to multiply two vectors to obtain all the possible cross products:

![IMG_20230804_115110](https://github.com/e3nn/e3nn/assets/42074085/edbc98fc-9251-48bc-9f47-7012279c6156)

**Comment by pfebrer** [comment]
In the diagram of what I need, when I commute the input factors, all output vectors should change sign.

**Comment by mariogeiger** [comment]
(I don't have my laptop here so I cannot verify what I'm saying) 
The ReducedTensorProduct will not assume the inputs to be the same, what you impose is the symmetry of the output. Maybe in your case you want an antisymmetric output. Try ij=-ji

**Comment by pfebrer** [comment]
If I do `ij=-ji` for this `2x1o [x] 2x1o` product, I get three vector outputs, which could be right, but I get only one scalar output. With my requirements, the picture with scalar outputs would be the same as with vector outputs, so I should have three different ones. In this case, the outputs would remain the same if I commute the inputs.

**Comment by mariogeiger** [comment]
Oh okay so you want to be symmetric for the scalar output but antisymmetric for the vector output. You have then to do that in two passes.

**Comment by pfebrer** [comment]
In general what I need is that in a product ` NxL_1 [x] NxL_1 = MxL_2` if I commute the input factors, the outputs behave as when commuting the factors in the individual product `1xL_1 [x] 1xL_1 = 1xL_2`.

So I thought about the `ElementWiseProduct`, but I think this could be acheived without restricting products only to element-wise pairs (or even same irreps features, because my inputs have multiple Ls). 

I'm realizing now that probably my proposal of a `FullyConnectedTensorProduct` with a symmetric weights matrix would not acheive this. Instead we would need a new tensor product as the one I picture above, like a full tensor product but where the permutations are averaged. After that tensor product we could use a linear layer. I don't know if this makes sense (?)

**Comment by pfebrer** [comment]
If you think of it in terms of symmetry of the output I believe it would mean:

`tp(x,y) = tp(y, x).T`

where tp returns the unreduced tensor product and `.T` is the transpose.

**Comment by mariogeiger** [comment]
I don't understand yet what you need. Maybe let me close this issue for now and I let you start a new discussion thread and restate what operation you want from scratch. 

(I think that `tp(x,y)=tp(y,x).T` is always true)
