### ISSUE TITLE
❓ [QUESTION]

### ISSUE THREAD

**Issue by 404notfound101** [e3nn/e3nn#415]
Hi e3nn team,

First of all, thanks for building this wonderful package! 

I am currently working on a GPU-memory-constrained project, and I noticed that most modules in e3nn are automatically compiled during initialization. I am not very familiar with the TorchScript compilation, so my question is whether the compilation module would require more memory. Another thing I noticed is that the compiled model doesn't seem compatible with float16 during the inference but looks good during training. 

All to say, is there a memory/speed trade-off when compiling modules (e.g. TensorProduct)? The compile_left_right argument in TensorProduct seems only accept True so If, by hypothesis, I can save any memory by avoiding compilation, how should I turn it off?

Thanks again for this hard work! Hope to hear back from you.

Luke Wu

**Comment by mariogeiger** [comment]
You can turn it off when you instantiate the module, here is an example:

```python
FullyConnectedTensorProduct(
            self.irreps_in,
            self.irreps_sh,
            self.irreps_out,
            shared_weights=False,
            compile_left_right=False,
            compile_right=True,
        )
```
