### ISSUE TITLE
`o3.selection_rule` should also include parity

### ISSUE THREAD

**Issue by blondegeek** [e3nn/e3nn#43]
Selection rules should also include whether change in parity is allowed. Then we can include this in `rs.tensor_product`.

https://github.com/e3nn/e3nn/blob/6d840edbf513e61678dae47b79d2fdf2454d68d9/e3nn/o3.py#L179-L188

**Comment by mariogeiger** [comment]
like done here

https://github.com/e3nn/e3nn/blob/77cb0949c217f31daf0dda1f36d08845b312721f/e3nn/kernel.py#L25-L27

**Comment by mariogeiger** [comment]
A slection rule for parity would simply be

```python
def selection_rule(p1, p2): 
     """ 
     selection rule for parity
     """ 
     return p1 * p2
```

**Comment by blondegeek** [comment]
Fixed in https://github.com/e3nn/e3nn/pull/44
