### ISSUE TITLE
Spherical Harmonics for degree higher than 11

### ISSUE THREAD

**Issue by FabianKTH** [e3nn/e3nn#433]
Hi everyone, first, thanks for all the work on this fantastic library. 

Do you have code for the spherical harmonics computation of degrees higher than 11 (even 12 or 13 would be great)? I'm currently researching the use of e3nn nets for brain diffusion MRI, and the fibre orientation functions are often given with l=6 such that a pre-computation of bases requires spherical harmonics up to l=12. 

Concretely, I'm referring to this function: https://github.com/e3nn/e3nn/blob/ac3528f7fb5fe1a8838f1df087d2eefe60d91ea8/e3nn/o3/_spherical_harmonics.py#L188 . 

Thanks a lot for any suggestions.

**Comment by mariogeiger** [comment]
Diffusion MRI data is so cool!

Check maybe the e3nn-jax code of the spherical harmonics. 

https://github.com/e3nn/e3nn-jax/tree/main/e3nn_jax/_src/spherical_harmonics

There are two algorithms to compute the SH, either by recursively computing a tensor product or by using the legendre polynomials. Maybe for around L=12 legendre might be preferable for the numerical stability.

**Comment by mariogeiger** [comment]
Still using pytorch, check the function `_generate_spherical_harmonics` in the same file you shared, it generates and prints the code for the spherical harmonics.

**Comment by FabianKTH** [comment]
This is great; thanks for the hint; now I get how to generate the relevant code. For this project, I'll have to stick with torch but gonna be aware of the developments in the jac version for future reference.

**Comment by mitkotak** [comment]
Just putting this here incase anyone is interested in writing up the integration interface: https://github.com/atomicarchitects/BAEsislib
