### ISSUE TITLE
❓ [QUESTION] How does e3nn model perform equivariance? 

### ISSUE THREAD

**Issue by smiles724** [e3nn/e3nn#443]
Hi, thanks for providing this helpful package. However, I encountered a issue that the 'gate_point_2021' model does not satisfy the naive equivariance. Can you give me some hints on this? 

![image](https://github.com/e3nn/e3nn/assets/39299863/479dfee2-a8f4-478e-b5e1-5cfd939204dc)
From the last block, you can see that the outputs are not consistent.

**Comment by mariogeiger** [comment]
Try with 4 points. 

And try out @ R.T

**Comment by smiles724** [comment]
> Try with 4 points.
> 
> And try out @ R.T

Thx, I will try with your advice!
