### ISSUE TITLE
Benchmark timing of various similar functions

### ISSUE THREAD

**Issue by blondegeek** [e3nn/e3nn#54]
- [ ] Test timing of linear_mod.Linear and kernel_mod.Kernel compared to those functions in linear and kernel respectively. This will help determine whether we should merge functions or keep separate due to memory / computation concerns.

**Comment by mariogeiger** [comment]
This might depend a lot on the application and device (cpu vs cuda)

**Comment by blondegeek** [comment]
Closing this with the intention of creating a better defined issue at a later date.
