### ISSUE TITLE
create cuda colab envrionment prepared for e3nn

### ISSUE THREAD

**Issue by bkmi** [e3nn/e3nn#72]
Like the title says. We should be able to run e3nn on colab with cuda acceleration easily.

**Comment by RealPolitiX** [comment]
Google colab has a native python version of 3.6.9, so it could be a hassle to make it compatible with e3nn now (need python 3.7 or higher).

**Comment by mariogeiger** [comment]
I actually don't really know if this dependency on python 3.7 that we've set is really necessary. Any clue? What changes from 3.6 to 3.7?

**Comment by mariogeiger** [comment]
https://colab.research.google.com/drive/1Gps7mMOmzLe3Rt_b012xsz4UyuexTKAf?usp=sharing

**Comment by blondegeek** [comment]
This is awesome! Thanks for figuring this out!

**Comment by bkmi** [comment]
nice! yay colab supporting 3.7

**Comment by mariogeiger** [comment]
Oh right! In the same time we also support 3.6 :-)
