### ISSUE TITLE
build manylinux cudaXY version

### ISSUE THREAD

**Issue by bkmi** [e3nn/e3nn#77]
I found how pytorch does their CI for new releases with the manylinux standard and different cuda version support. We should just copy this in my opinion.

https://github.com/pytorch/builder

**Comment by bkmi** [comment]
Hmm I cannot, for the life of me, figure out how pypi allows the `pip install torch=1.5.0+cu101` command. If anyone knows this, let me know.

**Comment by bkmi** [comment]
https://discuss.pytorch.org/t/distributing-software-which-depends-on-pytorch-with-custom-cuda-kernels/79526

**Comment by mariogeiger** [comment]
I am satisfied with the current solution
