### ISSUE TITLE
add functions for manipulating spherical tensors

### ISSUE THREAD

**Issue by blondegeek** [e3nn/e3nn#8]
add functions for rearranging spherical tensors such as `rearrange`, `split`, `sort`, `simplify` which will map an input `Rs` to a specified or default (in the case of `split`, `sort`, and `simplify`) `Rs`. These functions may be considered utilities.

**Comment by mariogeiger** [comment]
done in a686e7537c76bc5411485713cc103d29f381b6c6
for now I put them into SO3
