### ISSUE TITLE
Where did NormActivation go?

### ISSUE THREAD

**Issue by blondegeek** [e3nn/e3nn#93]
Looks like `NormActivation` disappeared. Can we please put it back?

**Comment by mariogeiger** [comment]
Do you use it? I think it’s a bad activation. 

I removed it for 3 reasons:
- I don’t recommend to use it
- the code was not up to date, the channel index was still not moved to the end
- it was not tested

**Comment by blondegeek** [comment]
I agree, however I'd like us to keep it since we used it in the original
tensor field networks paper.

**Comment by mariogeiger** [comment]
I will reimplement it in its simplest form as described in the paper:
![image](https://user-images.githubusercontent.com/333780/82534406-5cc9d000-9b45-11ea-8c07-fd43873feec4.png)
